version: "3"
services:
  postgres:
    container_name: helpdesk-postgres
    image: postgres:12.3
    ports:
      - "5432:5432"
    volumes: 
      - "./postgres_data:/var/lib/postgresql/data"
    environment:
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: helpdesk
  pgadmin:
    image: dpage/pgadmin4
    container_name: helpdesk-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 4041
    ports:
      - "4041:4041"